Add files via upload
Internationalize the beepmein script

diff --git a/bin/beepmein b/bin/beepmein
--- a/bin/beepmein
+++ b/bin/beepmein
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/usr/bin/env bash
+#
 #    beepmein - a simple alarm clock based on 'at'
 #    Copyright (C) 2019-2020 brontosaurusrex
 #
@@ -14,14 +15,79 @@
 #
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
+#
 # A little wrapper around linux 'at' command, that will beep you at specific time, see --help.
 # On Debian systems make sure 'at' is installed with --no-install-recommends.
+#
+########################################################################
+
+# https://github.com/BunsenLabs/bunsen-utilities
+
+
+# Internationalize the beepmein script
+
+TEXTDOMAIN="beepmein"
+TEXTDOMAINDIR="/usr/share/locale"
+
+export TEXTDOMAIN TEXTDOMAINDIR
+
+
+if ! command -v yad &> /dev/null; then
+
+  echo -e "\nThe yad program is not installed.\n"
+
+  exit 1
+
+fi
+
+logo="/usr/share/icons/Bunsen-lightdm/256x256/status/avatar-default.png"
+
+which gettext        1> /dev/null 2> /dev/null || { yad \
+--center \
+--window-icon "$logo" \
+--image=dialog-error \
+--timeout=10 \
+--no-buttons \
+--title "Warning" \
+--text "The gettext program is not installed." \
+--width="450" --height="100" \
+2>/dev/null   ; exit ; }
+
+
+
+
+for cmd in notify-send kill at speaker-test xrandr timeout ; do
+
+    if ! command -v "${cmd}" >/dev/null 2>&1; then
+        yad \
+            --center \
+            --window-icon "$logo" \
+            --image=dialog-error \
+            --timeout=10 \
+            --no-buttons \
+            --title "$(gettext "Warning")" \
+            --text "$(printf '%s\n' \
+                "$(gettext "The following required program is not installed: ")
+" \
+                "${cmd}")" \
+            --width="450" \
+            --height="100" \
+            2>/dev/null
+
+        exit 1
+    fi
+
+done
+
+
 
 # help
-help () {
-cat << EOF
-beepmein is a simple alarm clock based on 'at'
+
+help() {
+
+    local HELP
+
+    HELP="$(gettext 'beepmein is a simple alarm clock based on "at"
 
 Usage: beepmein [OPTIONS]
 
@@ -30,51 +96,61 @@ Two modes are available, "reminder" and "alarm".
 
 Options:
 
-beepmein now + 3 minutes # reminder ('at' time format)
+beepmein now + 3 minutes   # reminder ("at" time format)
 
-beepmein 22:10           # reminder ('at' time format)
+beepmein 22:10             # reminder ("at" time format)
 
-beepmein 3               # reminder (in 3 minutes, beepmein shortcut),
+beepmein 3                 # reminder (in 3 minutes, beepmein shortcut)
 
-beepmein 8:00 --alarm    # alarm (must be last parameter)
+beepmein 8:00 --alarm      # alarm (must be last parameter)
 
-beepmein --nr 5          # with no reason (must be first parameter)
+beepmein --nr 5            # with no reason (must be first parameter)
 
 beepmein --reason <reason> # pass reason (must be first & second parameters)
 
 Set sounds:
+
     (playback depends on mpv or vlc)
 
     --set-alarm <path/to/alarm.sound>
     --set-remind <path/to/reminder.sound>
 
 Test playback, blinking and notifications:
+
     --reaction reminder_text
     --reaction --alarm alarm_text
     --test # test everything
 
 List jobs:
+
     --list # or -l
 
 Kill all running playback/beeping:
+
     killall beepmein
 
 *Notes*
+
     at -l       # will list pending jobs (or atq)
-    at -r <num> # will remove job <num>  (or atrm)
+    at -r <num> # will remove job <num> (or atrm)
 
 External reference:
-    https://brontosaurusrex.github.io/2019/11/19/beepmein/
 
-EOF
+    https://brontosaurusrex.github.io/2019/11/19/beepmein/
+')"
+
+    printf '%s\n' "$HELP"
 }
 
+
 # help
+
 if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]] || [[ $# -eq 0 ]]; then
     help; exit
 fi
 
 # superecho
+
 superecho () {
     local msg="$1"
     if [[ -t 0 ]] ; then
@@ -85,25 +161,31 @@ superecho () {
 }
 
 # prepare config dir
+
 config="$HOME/.cache/beepmein"
-mkdir -p "$config" || superecho "$config not found, warning."
+
+mkdir -p "$config" || superecho "$(printf "$(gettext "%s not found, warning.")" "$config")"
 
 # var
 delay="0"
 
 # softlinks to audio samples
+
 alarmSample="$config/alarm"     # longer sample
 reminderSample="$config/remind" # shorter sample
 
 # Will kill all children with 'killall beepmein'
+
 trap 'kill $(jobs -p) >/dev/null 2>&1' EXIT
 
 # required
-command -v at >/dev/null 2>&1 || { >&2 echo "I need at: sudo apt install --no-install-recommends at" ; exit 1; }
-command -v speaker-test >/dev/null 2>&1 || { >&2 echo "I need speaker-test from alsa-utils (for reminder sound)." ; exit 1; }
-command -v notify-send >/dev/null 2>&1 || { >&2 echo "I need notify-send." ; exit 1; }
+
+command -v at >/dev/null 2>&1           || { >&2 echo "$(gettext "I need at: sudo apt install --no-install-recommends at")" ; exit 1; }
+command -v speaker-test >/dev/null 2>&1 || { >&2 echo "$(gettext "I need speaker-test from alsa-utils (for reminder sound).")" ; exit 1; }
+command -v notify-send >/dev/null 2>&1  || { >&2 echo "$(gettext "I need notify-send.")" ; exit 1; }
 
 # reminder sound, needs speaker-test (alsa-utils)
+
 beep () {
     local loops="$1"
     [[ -z "$loops" ]] && loops="1"
@@ -115,29 +197,35 @@ beep () {
 }
 
 # $1 = how many times to blink, $2 = pause between each blink
+
 blink () {
+
     # find primary connected or else 1st connected monitor
+
     monitor="$(xrandr -q | grep -w "connected" | grep "primary" | cut -f1 -d ' ')"
     if [[ -z "$monitor" ]]; then # no primary AND connected found, lets try 1st connected
         monitor="$(xrandr -q | grep -w "connected" | cut -f1 -d ' ')"
     fi
-    [[ -z "$monitor" ]] && { >&2 echo "No monitors found error" ; exit 1; }
+    [[ -z "$monitor" ]] && { >&2 echo "$(gettext "No monitors found error")" ; exit 1; }
 
     # find current brightness of that monitor
+
     now="$(xrandr --verbose | grep -A 15 "$monitor" | grep -i brightness | cut -f2 -d ' ')"
-    [[ -z "$now" ]] && { >&2 echo "Could not get current brightness error" ;  exit 1; }
+    [[ -z "$now" ]] && { >&2 echo "$(gettext "Could not get current brightness error")" ;  exit 1; }
 
     local blinks="$1"
     [[ -z "$blinks" ]] && blinks="1"
     for ((c=1; c<=blinks; c++))
     do
         # blink up
+
         for i in $(seq "$now" 0.2 3.0); do
             xrandr --output "$monitor" --brightness "$i"
             sleep 0.01
         done
 
         # blink down
+
         for i in $(seq 3.0 -0.2 "$now"); do
             xrandr --output "$monitor" --brightness "$i"
             sleep 0.01
@@ -151,6 +239,7 @@ blink () {
 }
 
 # alarm failsafe (by misko), this will be used if 'alarmSample' is not found.
+
 alarmfailsafe () {
 for ((i=1; i<=10; i++)); do
       for ((c=1;c<=3;c++)); do
@@ -162,11 +251,13 @@ done
 }
 
 # test alarm sample path (no test for reminder sample)
+
 testAlarmPath () {
-    [[ -f "$alarmSample" ]] || { >&2 superecho "Note: alarmSample $alarmSample not found, Internal fail-safe beep will be used instead."; }
+    [[ -f "$alarmSample" ]] || { >&2 superecho "$(printf "$(gettext "Note: alarmSample %s not found, Internal fail-safe beep will be used instead.")" "$alarmSample")"; }
 }
 
 # mpv or cvlc (by jr)
+
 playa () {
     file="$1"
     [[ -f $file ]] || { return 1; } # if no sample configured then return error, so that failsafe beeps can be used instead
@@ -177,31 +268,33 @@ playa () {
     then
         cvlc --quiet --no-video "$file" vlc://quit
     else
-        superecho "no player"
+        superecho "$(gettext "no player")"
         return 1
     fi
 }
 
 # test audio and notifications
+
 test () {
-    echo "notify test"
-    notify-send "notify test" || echo "failed"
+    echo "$(gettext "notify test")"
+    notify-send "$(gettext "notify test")" || echo "$(gettext "failed")"
     echo
-    echo "fail-safe internal beep test used for reminders"
-    beep "3" || echo "failed"
+    echo "$(gettext "fail-safe internal beep test used for reminders")"
+    beep "3" || echo "$(gettext "failed")"
     echo
-    echo "mpv sample test used for alarms (either this or vlc must pass)"
-    mpv --no-resume-playback --no-video --length=10 "$alarmSample" || echo "mpv failed"
+    echo "$(gettext "mpv sample test used for alarms (either this or vlc must pass)")"
+    mpv --no-resume-playback --no-video --length=10 "$alarmSample" || echo "$(gettext "mpv failed")"
     echo
-    echo "vlc sample test used for alarms"
-    cvlc --no-video --run-time=10 "$alarmSample" vlc://quit || echo "cvlc failed"
+    echo "$(gettext "vlc sample test used for alarms")"
+    cvlc --no-video --run-time=10 "$alarmSample" vlc://quit || echo "$(gettext "cvlc failed")"
     echo
-    echo "fail-safe internal beep test used for alarms"
-    alarmfailsafe || echo "failed"
+    echo "$(gettext "fail-safe internal beep test used for alarms")"
+    alarmfailsafe || echo "$(gettext "failed")"
     echo
 }
 
 # validate 'at' time syntax by generating fake job
+
 validate () {
 tmpjob="$(at "$1" <<<"test" 2>&1 | grep ^job | cut -f2 -d ' ')"
 if [[ -n "$tmpjob" ]]; then
@@ -214,11 +307,13 @@ fi
 }
 
 # test
+
 if [[ "$1" == "--test" ]]; then
     test; exit
 fi
 
 # list all 'at' jobs, last non-empty line only
+
 if [[ "$1" == "-l" ]] || [[ "$1" == "--list" ]]; then
     atq | sort -r | while read -r job rest ; do
         echo -n "$job $rest | "
@@ -228,31 +323,43 @@ if [[ "$1" == "-l" ]] || [[ "$1" == "--list" ]]; then
 fi
 
 # --set-alarm (via softlink)
+
 if [[ "$1" == "--set-alarm" ]]; then
+
     if [[ -z "$2" ]]; then
-        alarmpath="$(yad --on-top --center --title="Select alarm sample path" --file)"
+        alarmpath="$(yad --on-top --center --title="$(gettext "Select alarm sample path")" --file)"
     else
         alarmpath="$(readlink -f -- "$2")" # must be absolute path
     fi
-    [[ -f "$alarmpath" ]] || { superecho "No valid alarm path given." ; beep "2"; exit 1; }
+
+    [[ -f "$alarmpath" ]] || { superecho "$(gettext "No valid alarm path given.")" ; beep "2"; exit 1; }
+
     # f=force
     ln -fs "$alarmpath" "$config/alarm"
+
     exit
 fi
+
 # --set-remind (via softlink)
+
 if [[ "$1" == "--set-remind" ]]; then
+
     if [[ -z "$2" ]]; then
-        remindpath="$(yad --on-top --center --title="Select reminder sample path" --file)"
+        remindpath="$(yad --on-top --center --title="$(gettext "Select reminder sample path")" --file)"
     else
         remindpath="$(readlink -f -- "$2")" # must be absolute path
     fi
-    [[ -f "$remindpath" ]] || { superecho "No valid reminder path given." ; beep "2"; exit 1; }
+
+    [[ -f "$remindpath" ]] || { superecho "$(gettext "No valid reminder path given.")" ; beep "2"; exit 1; }
+
     # f=force
     ln -fs "$remindpath" "$config/remind"
+
     exit
 fi
 
 # main
+
 if [[ "$1" != "--reaction" ]] ; then
     if [[ "$1" == "--nr" ]] ; then       # --nr must be first
         # chop off first argument
@@ -278,23 +385,32 @@ if [[ "$1" != "--reaction" ]] ; then
     fi
 
     # validate at time format, exit if fails
-    validate "$attime" || { >&2 superecho "at time format error." ; beep "2"; exit 1; } # beep two times for error
+
+    validate "$attime" || { >&2 superecho "$(gettext "at time format error.")" ; beep "2"; exit 1; } # beep two times for error
 
     # user input reason
+
     if [[ $noreason != true ]]; then
-        read -rp "reason? " reason || reason="$(yad --on-top --center --title="beepmein" --width=300 --separator="" --form --field="reason?")"
+        read -rp "$(gettext "reason?") " reason || reason="$(yad --center --on-top --title="$(gettext "beepmein")" --separator="" --form --field="$(gettext "reason?")" --width="300")"
     fi
+
     [[ -z "$reason" ]] && reason="beep beep beep"
-    echo "beepmein: $attime, reason: $reason $alarm"
+
+    printf "$(gettext "beepmein: %s, reason: %s %s")" "$attime" "$reason" "$alarm" >&2
+
 
     # if custom input
+
     (( setdelay )) && delay="$(date +%_S.%N)"
 
     # set 'at'
-    at -M "$attime" <<< "$(echo "sleep $delay; DISPLAY=${DISPLAY} beepmein --reaction $alarm '${reason}'")" &>/dev/null || { superecho "at input error." ; beep "2"; exit 1; } # beep two times for error
+
+    at -M "$attime" <<< "$(echo "sleep $delay; DISPLAY=${DISPLAY} beepmein --reaction $alarm '${reason}'")" &>/dev/null || { superecho "$(gettext "at input error.")" ; beep "2"; exit 1; } # beep two times for error
 
 else
+
     # reaction
+
     shift
     if [ "$1" == "--alarm" ]; then
         shift
@@ -309,3 +425,4 @@ else
         wait
     fi
 fi
+
