Add files via upload
Internationalize the bl-conkymove script

diff --git a/bin/bl-conkymove b/bin/bl-conkymove
--- a/bin/bl-conkymove
+++ b/bin/bl-conkymove
@@ -1,5 +1,5 @@
-#!/bin/bash
-##
+#!/usr/bin/env bash
+#
 #    bl-conkymove: a script to set the position of a moveable Conky
 #    Copyright (C) 2016 xaos52  <xaos52@gmail.com>
 #    Copyright (C) 2015-2017 damo    <damo@bunsenlabs.org>
@@ -17,20 +17,70 @@
 #
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+########################################################################
 
-HELP="bl-conkymove is a script to set the position of a moveable Conky
+# https://github.com/BunsenLabs/bunsen-utilities
+
+
+# Internationalize the bl-conkymove script
+
+TEXTDOMAIN="bl-conkymove"
+TEXTDOMAINDIR="/usr/share/locale"
+
+export TEXTDOMAIN TEXTDOMAINDIR
+
+
+
+if ! command -v yad &> /dev/null; then
+
+  echo -e "\nThe yad program is not installed.\n"
+
+  exit 1
+
+fi
+
+logo="/usr/share/icons/Bunsen-lightdm/256x256/status/avatar-default.png"
+
+which gettext        1> /dev/null 2> /dev/null || { yad \
+--center \
+--window-icon "$logo" \
+--image=dialog-error \
+--timeout=10 \
+--no-buttons \
+--title "Warning" \
+--text "The gettext program is not installed." \
+--width="450" --height="100" \
+2>/dev/null   ; exit ; }
+
+
+which conky        1> /dev/null 2> /dev/null || { yad \
+--center \
+--window-icon "$logo" \
+--image=dialog-error \
+--timeout=10 \
+--no-buttons \
+--title "$(gettext "Warning")" \
+--text "$(gettext "The conky program is not installed.")" \
+--width="450" --height="100" \
+2>/dev/null   ; exit ; }
+
+
+HELP="$(gettext "bl-conkymove is a script to set the position of a moveable Conky
 
 Usage:  bl-conkymove
    or:  bl-conkymove -h|--help
 
 Optional arguments:
+
     -h | --help    Show this message (no other options are supported)
 
 After invoking the script, follow the displayed instructions
 to move a selected conky to a new position on the screen.
-"
+")"
 
 # look for a help option somewhere
+
 for i in "$@"
 do
     case "$i" in
@@ -42,11 +92,14 @@ do
 done
 
 error_exit(){
-    echo "$0 error: $1" >&2
+
+    printf "$(gettext "%s error: %s")" "$0" "$1" >&2
+
     exit 1
 }
 
 ## check necessary tools are installed
+
 required_commands=(xwininfo xprop yad) # array, space-separated words
 
 missing_commands=()
@@ -54,21 +107,26 @@ for i in "${required_commands[@]}"
 do
     hash $i || missing_commands+=(" $i")
 done
-[[ ${missing_commands[0]} ]] && error_exit "This script requires the following commands: ${missing_commands[*]}
+[[ ${missing_commands[0]} ]] && error_exit "$(printf "$(gettext "This script requires the following commands: %s
 Please install the packages containing the missing commands
-and rerun the script."
+and rerun the script.")" "${missing_commands[*]}")"
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
+
 if ! . "$BL_COMMON_LIBDIR/yad-includes" 2> /dev/null; then
-    echo $"Error: Failed to locate yad-includes in $BL_COMMON_LIBDIR" >&2
+
+    printf '%s\n' \
+    "$(printf "$(gettext 'Error: Failed to locate yad-includes in %s')" "$BL_COMMON_LIBDIR")" >&2
+
     exit 1
 fi
 
 #####FUNCTIONS#####
 
 # makes array "config"
+
 parse_conkyfile(){
-    [[ -f $1 ]] || { echo "$1 is not a file." >&2;return 1;}
+    [[ -f $1 ]] || { printf "$(gettext "%s is not a file.")" "$1" >&2;return 1;}
     unset config
     declare -Ag config
     local line parse=false comment=false conkyconf name value
@@ -122,8 +180,9 @@ parse_conkyfile(){
 
 # for version 1.09 conky files
 # makes array "config"
+
 parse_conkyfile_1.09(){
-    [[ -f $1 ]] || { echo "$1 is not a file." >&2;return 1;}
+    [[ -f $1 ]] || { printf "\n$(gettext "%s is not a file.")\n" "$1" >&2;return 1;}
     unset config
     declare -Ag config
     local name value
@@ -138,6 +197,7 @@ parse_conkyfile_1.09(){
 
 # usage: edit_conkyfile file name=value [name2=value2...]
 # parse_conkyfile should already have been run
+
 edit_conkyfile(){
     file=$1
     shift
@@ -149,7 +209,9 @@ edit_conkyfile(){
         value="${1#*=}"
         shift
         [[ ${config["$name"]+x} ]] || {
-            echo "$0: config key $name does not exist" >&2
+
+            printf "\n$(gettext "%s: config key %s does not exist")\n" "$0" "$name" >&2
+
             return 1
         }
         [[ ${config["$name"]} = "${value}" ]] && continue
@@ -168,6 +230,7 @@ edit_conkyfile(){
 # for version 1.09 conky files
 # usage: edit_conkyfile file name=value [name2=value2...]
 # parse_conkyfile should already have been run
+
 edit_conkyfile_1.09(){
     file=$1
     shift
@@ -179,7 +242,9 @@ edit_conkyfile_1.09(){
         value="${1#*=}"
         shift
         [[ ${config["$name"]+x} ]] || {
-            echo "$0: config key $name does not exist" >&2
+
+            printf "\n$(gettext "%s: config key %s does not exist")\n" "$0" "$name" >&2
+
             return 1
         }
         [[ ${config["$name"]//[[:space:]]} = "${value//[[:space:]]}" ]] && continue
@@ -238,20 +303,22 @@ getStart(){    #   Get initial Conky position
 
     redo_dialog(){
         echo "$0: $1" >&2
-        yad_error '--button=Exit:1' "$1\n\nChoose again?"
+        yad_error '--button='$(gettext "Exit")':1' "$(printf "$(gettext "%s
+
+Choose again?")" "$1")"
         if (( $? == 1 ));then
-            echo "  Cancelled: exiting..."
+            echo "  $(gettext "Cancelled: exiting...")"
             exit 0
         fi
         getStart
     }
 
     if [[ $CMD != conky ]];then
-        redo_dialog 'Selection is not a conky'
+        redo_dialog "$(gettext "Selection is not a conky")"
     elif [[ $CONKYPATH != /* ]];then
-        redo_dialog "$CONKYPATH is not an absolute path."
+        redo_dialog "$(printf "$(gettext "%s is not an absolute path.")" "$CONKYPATH")"
     else
-        #echo "Found a conky"
+        # echo "$(gettext "Found a conky")"
         posX_1=${info1[Absolute upper-left X]}
         posY_1=${info1[Absolute upper-left Y]}
     fi
@@ -275,8 +342,15 @@ getFinish(){   #   Get new Conky position
 
 getOffset(){   # parse_conkyfile should already have been run
     if [[ ${config[alignment]} = none ]];then   # placement managed by Openbox
-        yad_info "This Conky has 'alignment none'\nso placement is handled by the Window Manager.\n"
-        echo -e "\nConky has 'alignment none',\nso placement is handled by the Window Manager\nExiting...\n"
+
+        yad_info "$(gettext "This Conky has 'alignment none'
+so placement is handled by the Window Manager.
+")"
+
+        echo -e "\n$(gettext "Conky has 'alignment none',
+so placement is handled by the Window Manager
+Exiting...")"
+
         exit 0
     fi
 
@@ -317,10 +391,14 @@ cleanup() {
     if [[ $success = TRUE ]];then
         restore_wintype # backup file $BKP left, but will be overwritten on next run
     elif [[ -n $CONKYPATH && -f $BKP ]];then
-        echo "$0: exit, restoring original $CONKYPATH"
+
+        printf "$(gettext "%s: exit, restoring original %s")" "$0" "$CONKYPATH"
+
         mv "$BKP" "$CONKYPATH"
     else
-        echo "$0: exit, nothing to restore"
+
+        printf "$(gettext "%s: exit, nothing to restore")" "$0"
+
     fi
 }
 
@@ -339,8 +417,11 @@ trap cleanup EXIT
 # Not needed with conky 1.11.6-2 in Bullseye.
 #pkill -USR1 -x conky
 
-yad_question "To pick a conky, click 'Select Conky',\n\nthen click the 'xwininfo' cursor on the chosen conky\nto record its position." \
-     --button="Select Conky:0" --button="gtk-cancel:1"
+yad_question "$(gettext "To pick a conky, click 'Select Conky',
+
+then click the 'xwininfo' cursor on the chosen conky
+to record its position.")" \
+     --button="$(gettext "Select Conky"):0" --button="$(gettext "Cancel"):1"
 
 if (( $? == 0 ));then
     getStart
@@ -348,7 +429,9 @@ if (( $? == 0 ));then
     cp "$CONKYPATH" "$BKP"
     if ! grep -Eq '(^|[[:blank:]])conky\.config[[:blank:]]*=?' "$CONKYPATH"
     then
-        yad_info "This conky uses v1.09 syntax.\nIt is recommended to convert the conky to v1.10 syntax.\nSee: https://forums.bunsenlabs.org/viewtopic.php?id=3983"
+        yad_info "$(gettext "This conky uses v1.09 syntax.
+It is recommended to convert the conky to v1.10 syntax.
+See: https://forums.bunsenlabs.org/viewtopic.php?id=3983")"
         parse_conkyfile() {
             parse_conkyfile_1.09 "$@"
         }
@@ -357,7 +440,9 @@ if (( $? == 0 ));then
         }
     fi
 else
-    echo "  Cancelled: exiting..."
+
+    echo "  $(gettext "Cancelled: exiting...")"
+
     exit 0
 fi
 
@@ -365,13 +450,18 @@ parse_conkyfile "$CONKYPATH"
 
 adjust_wintype
 
-yad_question "Move the Conky to the desired location\nwith Alt+L-mousebutton Drag.\n\nThen click 'OK' to record the new position." \
-     --button="OK:0" --button="gtk-cancel:1"
+yad_question "$(gettext "Move the Conky to the desired location
+with Alt+L-mousebutton Drag.
+
+Then click 'OK' to record the new position.")" \
+     --button="$(gettext "OK"):0" --button="$(gettext "Cancel"):1"
 
 if (( $? == 0 ));then
     getFinish
 else
-    echo "  Cancelled: exiting..."
+
+    echo "  $(gettext "Cancelled: exiting...")"
+
     exit 0
 fi
 
@@ -382,3 +472,4 @@ edit_conkyfile "$CONKYPATH" "gap_x=$gapX" "gap_y=$gapY"
 success=TRUE
 
 exit
+
