Add files via upload
Internationalize the bl-conky-session script

diff --git a/bin/bl-conky-session b/bin/bl-conky-session
--- a/bin/bl-conky-session
+++ b/bin/bl-conky-session
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 #    bl-conky-session: read saved BunsenLabs Conky session file(s) and start the conkys
 #    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
@@ -24,6 +24,46 @@
 #      bl-conky-session &
 #
 ########################################################################
+
+
+# https://github.com/BunsenLabs/bunsen-utilities
+
+
+# Internationalize the bl-conky-session script
+
+TEXTDOMAIN="bl-conky-session"
+TEXTDOMAINDIR="/usr/share/locale"
+
+export TEXTDOMAIN TEXTDOMAINDIR
+
+
+logo="/usr/share/icons/Bunsen-lightdm/256x256/status/avatar-default.png"
+
+which gettext        1> /dev/null 2> /dev/null || { yad \
+--center \
+--window-icon "$logo" \
+--image=dialog-error \
+--timeout=10 \
+--no-buttons \
+--title "Warning" \
+--text "The gettext program is not installed." \
+--width="450" --height="100" \
+2>/dev/null   ; exit ; }
+
+
+which conky        1> /dev/null 2> /dev/null || { yad \
+--center \
+--window-icon "$logo" \
+--image=dialog-error \
+--timeout=10 \
+--no-buttons \
+--title "$(gettext "Warning")" \
+--text "$(gettext "The conky program is not installed.")" \
+--width="450" --height="100" \
+2>/dev/null   ; exit ; }
+
+
+
 CONKYPATH="$HOME/.config/conky"
 BLDEFAULT=$(readlink -f "$CONKYPATH/BL-Default-conky.conf") # BL-Default-conky.conf is a symlink to this release's default conky
 CONKYDEFAULT="$CONKYPATH/conky.conf" # not normally used
@@ -31,12 +71,14 @@ DEFAULTSESSFILE="$CONKYPATH/conky-sessionfile"
 STARTSESSION="$CONKYPATH/conky-startup-session" # symlink to chosen startup session (DEFAULTSESSFILE by default)
 SAVEDSESSIONS="$CONKYPATH/saved-sessions"    # list of saved sessions to be used by a pipemenu
 CUSTOMSESSION="$CONKYPATH/custom-session"
+
 # if a single non-default sessionfile is passed, it will be written to CUSTOMSESSION
 # conky-manager or other utilities might refer to it during the session
 # CUSTOMSESSION will be cleared if the default session or multiple sessions are run
 
 BKP_SFX=".$(date +"%Y%m%d-%H%M%S").conkysess~"
-USAGE='bl-conky-session is a script to parse saved BunsenLabs Conky session file(s)
+
+USAGE="$(gettext 'bl-conky-session is a script to parse saved BunsenLabs Conky session file(s)
 and start the conkys
 
 Usage: bl-conky-session [OPTION(S)]...FILES
@@ -48,6 +90,7 @@ Change the symlink to make a different sessionfile the default at startup.
 If not absolute, sessionfile paths are assumed to be relative to ~/.config/conky/
 
 Options:
+
         --default       : add the default sessionfile to a list of files
             sessionfile1  sessionfile2 etc
         --kill-running  : kill current running conkys without prompting
@@ -57,6 +100,7 @@ Options:
             (An asterisk is appended to the current startup session.)
 
 Examples:
+
     Run default sessionfile at login:
 
             "bl-conky-session &"
@@ -79,9 +123,10 @@ Examples:
 
     Restore HOME/.config/conky/conky-sessionfile as startup session:
             "bl-conky-session --set-startup default"
-'
+')"
 
 # look for a help option somewhere
+
 for i in "$@"
 do
     case "$i" in
@@ -93,11 +138,12 @@ do
 done
 
 ### DIALOG VARIABLES
+
 DLG="yad --center --undecorated --borders=20 "
-TITLE="BunsenLabs Conky Session"
+TITLE="$(gettext "BunsenLabs Conky Session")"
 WINICON="--window-icon=distributor-logo-bunsenlabs"
-OK="--button=OK:0"
-CANCEL="--button=gtk-cancel:1"
+OK="--button=$(gettext "OK"):0"
+CANCEL="--button=$(gettext "Cancel"):1"
 
 ########################################################################
 
@@ -106,8 +152,8 @@ killConkys(){
         if ((kill)); then
             killall -u "$USER" conky && sleep 0.2s || return 1
         else
-            MSG="Kill running conkys first?"
-            $DLG $WINICON --title="$TITLE" --text="$MSG" "$CANCEL" --button="Don't kill":2 "$OK"
+            MSG="$(gettext "Kill running conkys first?")"
+            $DLG $WINICON --title="$TITLE" --text="$MSG" "$CANCEL" --button="$(gettext "Don't kill")":2 "$OK"
             case $? in
             0)            # kill all conkys
                 killall -u "$USER" conky && sleep 0.2s || return 1
@@ -124,11 +170,14 @@ killConkys(){
 }
 
 # usage: loadSession <sessionfile>
+
 loadSession(){
     local sessfile CPATH_REGEX WMC_REGEX needRewrite conkys c path target
     sessfile=$1
     [[ ! -f $sessfile ]] || ! grep -q '[^[:space:]]' "$sessfile" && {
-        echo "${0}: WARNING $sessfile is empty or does not exist" >&2
+
+        printf "$(gettext '%s: WARNING %s is empty or does not exist')" "${0}" "$sessfile" >&2
+
         return 1
     }
     CPATH_REGEX="-c[[:blank:]]+(.*(conky.*\.conf|conky|conkyrc))([[:blank:]]+|$)"
@@ -141,7 +190,9 @@ loadSession(){
             if [[ $c =~ $CPATH_REGEX ]]; then
                 conkys[i]=${BASH_REMATCH[1]} # rewrite with filepath only
             else
-                echo "$0: WARNING: failed to parse line $c in $sessfile" >&2
+
+                printf "$(gettext "%s: WARNING: failed to parse line %s in %s")" "$0" "$c" "$sessfile" >&2
+
                 conkys[i]='' # discard line
             fi
             needRewrite=true
@@ -149,7 +200,7 @@ loadSession(){
             if [[ $c =~ ${WMC_REGEX}.*${CPATH_REGEX} ]]; then
                 conkys[i]="D[${BASH_REMATCH[1]}] ${BASH_REMATCH[2]}" # format: 'D[<desktop>] <path>'
             else
-                echo "$0: WARNING: failed to parse line $c in $sessfile" >&2
+                printf "$(gettext "%s: WARNING: failed to parse line %s in %s")" "$0" "$c" "$sessfile" >&2
                 conkys[i]='' # discard line
             fi
             needRewrite=true
@@ -160,7 +211,9 @@ loadSession(){
     if [[ $needRewrite = true ]]; then # should only happen once, except if restoring old-style BLOBs
         target=$(readlink -f "$sessfile") # in case $sessfile is a symlink
         needBackup "$target" && cp "$target" "${target}${BKP_SFX}" # make backup
-        echo "$0: reformatting $sessfile"
+
+        printf "$(gettext "%s: reformatting %s")" "$0" "$sessfile" >&2
+
         :> "$sessfile"
         for path in "${conkys[@]}"; do
             [[ -n $path ]] || continue
@@ -182,14 +235,17 @@ fullPath(){
             path="$HOME/$path"
         fi
     fi
-    [[ -r $path ]] || { echo "$0: WARNING: cannot read $path" >&2 ; return 1;}
+    [[ -r $path ]] || { printf "\n$(gettext "%s: WARNING: cannot read %s")\n" "$0" "$path" >&2 ; return 1;}
+
     printf '%s' "$path"
 }
 
 launchConkys(){
     local WINID_REGEX path desktop datafile
     WINID_REGEX='drawing to created window \((0[xX][0-9a-fA-F]+)\)'
-    (( ${#ALL_CONKYS[@]} > 0 )) || { echo "$0: no conkys to launch"; return 0;}
+
+    (( ${#ALL_CONKYS[@]} > 0 )) || { printf "\n$(gettext "%s: no conkys to launch")\n" "$0"; return 0;}
+
     set -m # enable job control so forked conkys are immune to signals (although unnecessary when conky is forked to background in config)
     for path in "${!ALL_CONKYS[@]}"; do
         case ${path%% *} in # first word
@@ -210,21 +266,28 @@ launchConkys(){
                 ;;
             wayland)
                 ((desktop++)) # labwc starts desktop count from 1
+
                 # only conkys running on xwayland can be sent to a specific desktop
                 # wmctrl runs on xwayland, and errors out if it doesn't know about the window id
+
                 if wmctrl -i -a "$id" >/dev/null 2>&1 # raise conky and get focus
                 then
-                    echo "conky $id is running on xwayland"
+
+                    printf "$(gettext "conky %s is running on xwayland")" "$id"
+
                     wtype -M win -M alt -k "$desktop" # SendToDesktop keybind must be configured in labwc's rc.xml
                 else
-                     echo "conky $id is not on xwayland"
-                     continue
+
+                    printf "$(gettext "conky %s is not on xwayland")" "$id"
+
+                    continue
                 fi
                 ;;
             esac
             rm "$datafile"
             ;;
         *) # assume line is a clean filepath
+
             path=$( fullPath "$path" ) || continue
             conky -c "$path" >/dev/null 2>&1 &
             disown
@@ -239,13 +302,18 @@ setStartup(){
     local sessfile="$1"
     [[ $sessfile = default ]] && sessfile="$DEFAULTSESSFILE"
     sessfile=$( fullPath "$sessfile" ) || {
-        echo "$0: ERROR: cannot set session file $sessfile as startup, it does not exist." >&2
+
+        printf "$(gettext "%s: ERROR: cannot set session file %s as startup, it does not exist.")" "$0" "$sessfile" >&2
+
         return 1
     }
-    ln -s -f "$sessfile" "$STARTSESSION" || { echo "$0: ERROR: failed to create symlink $STARTSESSION" >&2; return 1;}
+
+    ln -s -f "$sessfile" "$STARTSESSION" || { printf "\n$(gettext "%s: ERROR: failed to create symlink %s")\n" "$0" "$STARTSESSION" >&2; return 1;}
+
 }
 
 # generate output for terminal
+
 listSessfiles(){
     local startup
     local -a sessfiles
@@ -262,7 +330,7 @@ listSessfiles(){
             fi
         done
     else
-        echo "Cannot find any session files"
+        echo -e "\n$(gettext "Cannot find any session files")\n"
     fi
 }
 
@@ -270,6 +338,7 @@ listSessfiles(){
 # Check if an identical backed-up file already exists in same directory.
 # Return 1 if found (no backup needed before overwrite),
 # otherwise return 0 (do backup).
+
 needBackup(){
     local file bkp_file
     file=$1
@@ -277,7 +346,9 @@ needBackup(){
     do
         [[ -f $bkp_file ]] || continue
         diff -BEbZ "$file" "$bkp_file" >/dev/null && {
-            #debug "$file already has identical backup ${bkp_file}, no need to backup again"
+
+            # debug "$file already has identical backup ${bkp_file}, no need to backup again"
+
             return 1
         }
     done
@@ -287,22 +358,32 @@ needBackup(){
 ########################################################################
 
 if ! grep -q '[^[:space:]]' "$DEFAULTSESSFILE" 2>/dev/null ; then
-    echo "$0: There is no default session file: ${DEFAULTSESSFILE}, generating now..." >&2
+
+    printf "$(gettext "%s: There is no default session file: %s, generating now...")" "$0" "${DEFAULTSESSFILE}" >&2
+
     if [[ -f $BLDEFAULT ]]; then
         echo "${BLDEFAULT#"$HOME"/}" > "$DEFAULTSESSFILE" # use relative path in session file for better compatibility with BLOB
     elif [[ -f $CONKYDEFAULT ]]; then
-        echo "$0: $BLDEFAULT not found, using $CONKYDEFAULT in session file." >&2
+
+        printf "$(gettext "%s: %s not found, using %s in session file.")" "$0" "$BLDEFAULT" "$CONKYDEFAULT" >&2
+
         echo "${CONKYDEFAULT#"$HOME"/}" > "$DEFAULTSESSFILE"
+
     else
-        echo "$0: ERROR: unable to generate default session file." >&2
+
+        printf "$(gettext "%s: ERROR: unable to generate default session file.")" "$0" >&2
+
         exit 1
     fi
 fi
 
 # user can use --set-startup to change STARTSESSION symlink to make any sessfile the startup default
+
 if [[ ! -f $STARTSESSION ]]; then
-    echo "$0: generating missing symlink $STARTSESSION to $DEFAULTSESSFILE"
-    ln -s "$DEFAULTSESSFILE" "$STARTSESSION" || echo "$0: WARNING: failed to create symlink $STARTSESSION" >&2
+
+    printf "$(gettext "%s: generating missing symlink %s to %s")" "$0" "$STARTSESSION" "$DEFAULTSESSFILE" >&2
+
+    ln -s "$DEFAULTSESSFILE" "$STARTSESSION" || printf "\n$(gettext "%s: WARNING: failed to create symlink %s")\n" "$0" "$STARTSESSION" >&2
 fi
 
 kill=0 # will evaluate with arithmetic command, so 1 = true
@@ -332,7 +413,7 @@ do
         sessions["$STARTSESSION"]=1
         ;;
     -*)
-        echo "$0: ${1}: no such option"$'\n' >&2
+        printf "\n$(gettext "%s: %s: no such option")\n" "$0" "${1}"  >&2
         echo -e "$USAGE"
         exit 1
         ;;
@@ -343,7 +424,7 @@ do
             sessions["$arg"]=1
             customsess=$arg # not an array: will be overwritten with each added non-default session
         else
-            echo "$0: WARNING: session file $arg does not exist." >&2
+            printf "$(gettext "%s: WARNING: session file %s does not exist.")" "$0" "$arg" >&2
         fi
         ;;
     esac
@@ -368,3 +449,4 @@ else
 fi
 
 launchConkys
+
