Add files via upload
Internationalize the bl-restart script

diff --git a/bin/bl-restart b/bin/bl-restart
--- a/bin/bl-restart
+++ b/bin/bl-restart
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 #    bl-restart: a script to restart all instances of a process name
 #    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
@@ -16,24 +16,65 @@
 #
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+########################################################################
 
-HELP='bl-restart is a script to restart all running instances of
+
+# https://github.com/BunsenLabs/bunsen-utilities
+
+
+# Internationalize the bl-restart script
+
+TEXTDOMAIN="bl-restart"
+TEXTDOMAINDIR="/usr/share/locale"
+
+export TEXTDOMAIN TEXTDOMAINDIR
+
+
+if ! command -v yad &> /dev/null; then
+
+  echo -e "\nThe yad program is not installed.\n"
+
+  exit 1
+
+fi
+
+logo="/usr/share/icons/Bunsen-lightdm/256x256/status/avatar-default.png"
+
+which gettext        1> /dev/null 2> /dev/null || { yad \
+--center \
+--window-icon "$logo" \
+--image=dialog-error \
+--timeout=10 \
+--no-buttons \
+--title "Warning" \
+--text "The gettext program is not installed." \
+--width="450" --height="100" \
+2>/dev/null   ; exit ; }
+
+
+
+HELP="$(gettext "bl-restart is a script to restart all running instances of
 any process name passed
 
 Usage: bl-restart <name>
    or: bl-restart -h|--help
 
 Optional arguments:
+
     -h | --help  Show this message (no other options are supported at this time)
 
 Each running process is stopped with SIGTERM.
 
 All previously running commands are then re-run, forked and disowned,
 with any duplicates removed.
-'
+")"
+
 wait_timeout=10s
 
+
 # look for a help option somewhere
+
 for i in "$@"
 do
     case "$i" in
@@ -47,7 +88,9 @@ done
 name=$1
 
 pgrep -x -u "$USER" "$name" >/dev/null || {
-    echo "$0: no $name processes running"
+
+    printf "\n$(gettext "%s: no %s processes running")\n" "$0" "$name"
+
     exit 0
 }
 
@@ -55,18 +98,19 @@ declare -A commands # associative array
 tailpids=()
 index=1
 while read -r pid cmd; do
-    [[ -n $pid ]] || { echo "$0: no $name processes found belonging to $USER" >&2; exit 1;}
+    [[ -n $pid ]] || { printf "\n$(gettext "%s: no %s processes found belonging to %s")\n" "$0" "$name" "$USER" >&2; exit 1;}
     commands["$cmd"]=C${index} # duplicate commands will be launched only once
     mapfile -d '' -t "C${index}" < "/proc/${pid}/cmdline" # use NULL delimiter to split cmdline into array C$index
     (( index++ ))
-    kill -TERM "$pid" || { echo "$0: ERROR: failed to kill $pid" >&2; exit 1;}
+    kill -TERM "$pid" || { printf "\n$(gettext "%s: ERROR: failed to kill %s")\n" "$0" "$pid" >&2; exit 1;}
     tail -f /dev/null --pid="$pid" & tailpids+=($!) # wait in background for process to die
 done <<< "$(pgrep -ax "$name" -u "$USER")"
+
 # an extra "tail" process for each killed process is the price of being able to "wait" for them to close
 # "wait" can only wait for children of this script
 
 trap 'exit 1' SIGUSR1
-{ sleep $wait_timeout; echo "$0: Some processes still running after $wait_timeout, killing $0" >&2; kill -s SIGUSR1 $$; } & sleep_pid=$!
+{ sleep $wait_timeout; printf "$(gettext "%s: Some processes still running after %s, killing %s")" "$0" "$wait_timeout" "$0" >&2; kill -s SIGUSR1 $$; } & sleep_pid=$!
 
 wait "${tailpids[@]}" # wait till all forked tail commands have terminated
 
@@ -76,6 +120,7 @@ wait "$sleep_pid" >/dev/null # suppress "terminated" message after killing
 set -m # enable job control so forked processes are immune to signals from script
 
 declare -n CMD # CMD is a nameref
+
 for CMD in "${commands[@]}" # CMD will refer to each array name in turn
 do
     "${CMD[@]}" >/dev/null 2>&1 &
@@ -84,3 +129,4 @@ do
 done
 
 set +m
+
