Add files via upload
Internationalize the bl-setlocale script

diff --git a/bin/bl-setlocale b/bin/bl-setlocale
--- a/bin/bl-setlocale
+++ b/bin/bl-setlocale
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 #    bl-setlocale: a script to choose a user locale
 
@@ -25,12 +25,75 @@
 # BunsenLabs ships a fix for this when LightDM is being used,
 # but something more generic would be nice.
 
-HELP='bl-setlocale is a GUI (yad) script to set a user locale
+########################################################################
+
+
+# https://github.com/BunsenLabs/bunsen-utilities
+
+
+# Internationalize the bl-setlocale script
+
+TEXTDOMAIN="bl-setlocale"
+TEXTDOMAINDIR="/usr/share/locale"
+
+export TEXTDOMAIN TEXTDOMAINDIR
+
+
+if ! command -v yad &> /dev/null; then
+
+  echo -e "\nThe yad program is not installed.\n"
+
+  exit 1
+
+fi
+
+logo="/usr/share/icons/Bunsen-lightdm/256x256/status/avatar-default.png"
+
+which gettext        1> /dev/null 2> /dev/null || { yad \
+--center \
+--window-icon "$logo" \
+--image=dialog-error \
+--timeout=10 \
+--no-buttons \
+--title "Warning" \
+--text "The gettext program is not installed." \
+--width="450" --height="100" \
+2>/dev/null   ; exit ; }
+
+
+
+
+for cmd in sed pgrep dbus-send locale notify-send ; do
+
+    if ! command -v "${cmd}" >/dev/null 2>&1; then
+        yad \
+            --center \
+            --window-icon "$logo" \
+            --image=dialog-error \
+            --timeout=10 \
+            --no-buttons \
+            --title "$(gettext "Warning")" \
+            --text "$(printf '%s\n' \
+                "$(gettext "The following required program is not installed: ")
+" \
+                "${cmd}")" \
+            --width="450" \
+            --height="100" \
+            2>/dev/null
+
+        exit 1
+    fi
+
+done
+
+
+HELP="$(gettext 'bl-setlocale is a GUI (yad) script to set a user locale
 
 Usage:  bl-setlocale
    or:  bl-setlocale -h|--help
 
 Optional arguments:
+
     -h | --help    Show this message (no other options are supported at this time)
 
 Without options, the user will be shown a list of locales installed
@@ -41,13 +104,15 @@ if the daemon is running.
 It is necessary to log out and back in to use the new locale.
 
 *NOTE*
+
 The LightDM GTK greeter already offers a locale chooser widget,
 making this utility unnecessary. However, other interfaces,
 such as slick-greeter, do not have any such facility, hence this script.
 
-'
+')"
 
 # if help option anywhere in args, output $HELP and exit immediately
+
 for i in "$@"
 do
     case "$i" in
@@ -59,14 +124,17 @@ do
 done
 
 dm_file="$HOME/.dmrc"
+
 [[ -e "$dm_file" ]] || touch "$dm_file"
 
 yad_info(){
-    yad --window-icon=distributor-logo-bunsenlabs --center --borders=20 --undecorated --fixed --on-top --button=OK:0 --text "$*"
+    yad --center --window-icon=distributor-logo-bunsenlabs --borders=20 --undecorated --fixed --on-top --button=$(gettext "OK"):0 --text "$*"
 }
 
 error_exit() {
-    yad_info "$0 error:"$'\n'"$*"
+    yad_info "$(printf "$(gettext "%s error:
+%s")\n" "$0" "$*")"
+
     exit 1
 }
 
@@ -75,36 +143,46 @@ parse_dmrc() {
 }
 
 # pass locale (LANG) to be written
+
 write_dmrc() {
     sed -i '/[Ll]anguage=/d' "$dm_file"
     echo "Language=$1" >> "$dm_file"
 }
 
 # pass same locale as for write_dmrc
+
 write_accountsservice() {
     pgrep -x 'accounts-daemon' >/dev/null || {
-        echo "${0}: accounts-daemon is not running, accountsservice language will not be updated." >&2
+
+        printf "$(gettext "%s: accounts-daemon is not running, accountsservice language will not be updated.")" "${0}" >&2
+
         return 1
     }
     local lang=${1/utf8/UTF-8}
+
     # put returned path in array to strip leading & trailing spaces
-    local user_path=($(dbus-send --print-reply=literal --system --dest=org.freedesktop.Accounts /org/freedesktop/Accounts org.freedesktop.Accounts.FindUserByName string:"$USER")) || error_exit "error finding ${USER}'s accountsservice path"
-    dbus-send --system --dest=org.freedesktop.Accounts "${user_path[0]}" org.freedesktop.Accounts.User.SetLanguage string:"$lang" || error_exit "error setting ${USER}'s language in accountsservice"
+
+    local user_path=($(dbus-send --print-reply=literal --system --dest=org.freedesktop.Accounts /org/freedesktop/Accounts org.freedesktop.Accounts.FindUserByName string:"$USER")) || error_exit "$(printf "$(gettext "error finding %s's accountsservice path")" "${USER}")"
+
+    dbus-send --system --dest=org.freedesktop.Accounts "${user_path[0]}" org.freedesktop.Accounts.User.SetLanguage string:"$lang" || error_exit "$(printf "$(gettext "error setting %s's language in accountsservice")" "${USER}")"
 }
 
 parse_dmrc
 
-locale_prompt="Your current locale is <b>${current_lang:-not set}</b>
+locale_prompt="$(gettext "Your current locale is %s
 These are the locales you have enabled;
-to add more: <i>sudo dpkg-reconfigure locales</i>
+to add more: %s
 
-Please choose:"
+Please choose:")"
+
 
 #### parse locale ####
+
 list=()
 locale_regex="^[[:blank:]]*locale:[[:blank:]]*([^[:blank:]]+)"
 name_regex="^[[:blank:]]*language \| (.*)$"
 parsing=true
+
 while read -r line
 do
     [[ $line =~ $locale_regex ]] && {
@@ -123,26 +201,46 @@ do
         parsing=false
     }
 done < <(locale -av)
+
 ########
 
-choice=$( yad --title 'Choose language' --window-icon=distributor-logo-bunsenlabs --center --borders=20 --geometry 350x350 --button=OK:0 --button=Cancel:1 --text "$locale_prompt" --no-headers --separator='' --list --print-column=1 --column="locale":TEXT --column="name":TEXT "${list[@]}" )
+choice=$( yad \
+--center \
+--window-icon=distributor-logo-bunsenlabs \
+--title "$(gettext "Choose language")" \
+--borders=20 --geometry 350x350 \
+--text "$(printf "$locale_prompt" "<b>${current_lang:-not set}</b>" "<i>sudo dpkg-reconfigure locales</i>")" \
+--no-headers \
+--separator='' \
+--list \
+--print-column=1 --column="$(gettext "locale")":TEXT --column="$(gettext "name")":TEXT "${list[@]}" \
+--button=$(gettext "OK"):0 --button=$(gettext "Cancel"):1)
 case $? in
 0)
     extra_info=
     write_dmrc "$choice"
     write_accountsservice "$choice" && extra_info=' and accountsservice'
     parse_dmrc
+
     [[ "$current_lang" = "$choice" ]] || {
-        yad_info "Error setting language. Please check ~/dmrc"
+
+        yad_info "$(gettext "Error setting language. Please check ~/dmrc")"
+
         exit 1
     }
-    yad_info "Your locale has been set to <b>${choice}</b> in ~/.dmrc${extra_info:-}. \nThe change will be seen after your next login."
+
+    yad_info "$(printf "$(gettext "Your locale has been set to %s in ~/.dmrc%s.
+The change will be seen after your next login.")" "<b>${choice}</b>" "${extra_info:-}")"
+
     ;;
 1)
-    notify-send "Choose language" "Change cancelled"
+    notify-send "$(gettext "Choose language" "Change cancelled")"
     ;;
 *)
-    yad_info "$0 returned an error..."
+    yad_info "$(printf "$(gettext "%s returned an error...")" "$0")"
+
     exit 1
+
     ;;
 esac
+
