Add files via upload
Internationalize the bl-tint2-edit script

diff --git a/bin/bl-tint2-edit b/bin/bl-tint2-edit
--- a/bin/bl-tint2-edit
+++ b/bin/bl-tint2-edit
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 #    bl-tintedit: a BunsenLabs tint2 config file editor
 #    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
@@ -26,29 +26,92 @@
 #
 ########################################################################
 
+# https://github.com/BunsenLabs/bunsen-utilities
+
+
+# Internationalize the bl-tint2-edit script
+
+TEXTDOMAIN="bl-tint2-edit"
+TEXTDOMAINDIR="/usr/share/locale"
+
+export TEXTDOMAIN TEXTDOMAINDIR
+
+
+if ! command -v yad &> /dev/null; then
+
+  echo -e "\nThe yad program is not installed.\n"
+
+  exit 1
+
+fi
+
+logo="/usr/share/icons/Bunsen-lightdm/256x256/status/avatar-default.png"
+
+which gettext        1> /dev/null 2> /dev/null || { yad \
+--center \
+--window-icon "$logo" \
+--image=dialog-error \
+--timeout=10 \
+--no-buttons \
+--title "Warning" \
+--text "The gettext program is not installed." \
+--width="450" --height="100" \
+2>/dev/null   ; exit ; }
+
+
+
+
+for cmd in tint2 bl-text-editor; do
+
+    if ! command -v "${cmd}" >/dev/null 2>&1; then
+        yad \
+            --center \
+            --window-icon "$logo" \
+            --image=dialog-error \
+            --timeout=10 \
+            --no-buttons \
+            --title "$(gettext "Warning")" \
+            --text "$(printf '%s\n' \
+                "$(gettext "The following required program is not installed: ")
+" \
+                "${cmd}")" \
+            --width="450" \
+            --height="100" \
+            2>/dev/null
+
+        exit 1
+    fi
+
+done
+
+
 TINT2PATH="$HOME/.config/tint2"
 
-HELP="bl-tint2edit is a script to edit selected tint2 config files
+
+HELP="$(gettext "bl-tint2edit is a script to edit selected tint2 config files
 which are displayed in a yad window with checkboxes.
 
 Usage:  bl-tint2edit
    or:  bl-tint2edit -h|--help
 
 Optional arguments:
+
     -h | --help    Show this message (no other options are supported at this time)
 
-Tint2 files must be in $TINT2PATH
+Tint2 files must be in %s
 
 Checkmarked tint2s will be opened in the text editor.
 Multiple tint2s can be chosen.
-"
+")"
+
 
 ### DIALOG VARIABLES
+
 DLGDEC="yad --center  --borders=20 --width=400 --height=500 "
-TITLE="BunsenLabs Tint2 Edit"
+TITLE="$(gettext "BunsenLabs Tint2 Edit")"
 WINICON="--window-icon=distributor-logo-bunsenlabs"
-OK="--button=OK:0"
-CANCEL="--button=gtk-cancel:1"
+OK="--button=$(gettext "OK"):0"
+CANCEL="--button=$(gettext "Cancel"):1"
 
 ########## FUNCTIONS ###################################################
 
@@ -69,32 +132,44 @@ findTints(){
 ######## END FUNCTIONS #################################################
 
 # look for a help option somewhere
+
 for i in "$@"
 do
     case "$i" in
     -h|--help)
-        echo "$HELP"
+
+        printf "$HELP" "$TINT2PATH"
+
         exit 0
         ;;
     esac
 done
 
 BL_COMMON_LIBDIR='/usr/lib/bunsen/common'
+
 if ! . "$BL_COMMON_LIBDIR/bl-includes" 2> /dev/null; then
-    echo $"Error: Failed to locate bl-includes in $BL_COMMON_LIBDIR" >&2
+
+    printf '%s\n' \
+    "$(printf "$(gettext 'Error: Failed to locate bl-includes in %s')" "$BL_COMMON_LIBDIR")" >&2
+
     exit 1
 fi
+
 # pangoEscape() for yad text display of filenames
 # is provided in bl-includes
 
 # get tint2s in TINT2PATH, recursively, add to array LISTTINT
+
 findTints
 
 ## Populate yad dialog from array, get choice(s)
+
 choice=$( $DLGDEC $WINICON --list --title="$TITLE" \
-    --text="Select Tint2s to edit from the list\nMultiple Tint2s can be chosen\n" \
+    --text="$(gettext "Select Tint2s to edit from the list
+Multiple Tint2s can be chosen
+")" \
     --checklist --separator='' --no-selection \
-    --column="Select:CHK" --column="Tint2 Name:TEXT" --column="path:HD" "${LISTTINT[@]}" \
+    --column="$(gettext "Select"):CHK" --column="$(gettext "Tint2 Name"):TEXT" --column="$(gettext "path"):HD" "${LISTTINT[@]}" \
     --print-column=3 $OK $CANCEL )
 
 if [[ $? == 1 ]]; then # cancel button pressed
@@ -108,3 +183,4 @@ else
     done <<< "$choice"
     bl-text-editor "${paths[@]}"
 fi
+
