Add files via upload
Internationalize the bl-tint2-session script

diff --git a/bin/bl-tint2-session b/bin/bl-tint2-session
--- a/bin/bl-tint2-session
+++ b/bin/bl-tint2-session
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 #    bl-tint2-session: a script to read a saved Tint2 session file
 #     and start the tint2s
@@ -24,15 +24,80 @@
 #      bl-tint2-session
 #
 ########################################################################
+
+
+
+# https://github.com/BunsenLabs/bunsen-utilities
+
+
+# Internationalize the bl-tint2-session script
+
+TEXTDOMAIN="bl-tint2-session"
+TEXTDOMAINDIR="/usr/share/locale"
+
+export TEXTDOMAIN TEXTDOMAINDIR
+
+
+if ! command -v yad &> /dev/null; then
+
+  echo -e "\nThe yad program is not installed.\n"
+
+  exit 1
+
+fi
+
+logo="/usr/share/icons/Bunsen-lightdm/256x256/status/avatar-default.png"
+
+which gettext        1> /dev/null 2> /dev/null || { yad \
+--center \
+--window-icon "$logo" \
+--image=dialog-error \
+--timeout=10 \
+--no-buttons \
+--title "Warning" \
+--text "The gettext program is not installed." \
+--width="450" --height="100" \
+2>/dev/null   ; exit ; }
+
+
+
+
+for cmd in tint2 pkill; do
+
+    if ! command -v "${cmd}" >/dev/null 2>&1; then
+        yad \
+            --center \
+            --window-icon "$logo" \
+            --image=dialog-error \
+            --timeout=10 \
+            --no-buttons \
+            --title "$(gettext "Warning")" \
+            --text "$(printf '%s\n' \
+                "$(gettext "The following required program is not installed: ")
+" \
+                "${cmd}")" \
+            --width="450" \
+            --height="100" \
+            2>/dev/null
+
+        exit 1
+    fi
+
+done
+
+
+
 TINT2PATH="$HOME/.config/tint2"
 DEFAULTTINT2=$(readlink -f "${TINT2PATH}/tint2rc") # tint2rc is a symlink to this release's default tint2 file
 SESSIONFILE="$TINT2PATH/tint2-sessionfile"
-USAGE='bl-tint2-session is a script to parse a saved Tint2 session file
+
+USAGE="$(gettext 'bl-tint2-session is a script to parse a saved Tint2 session file
 and start the tint2s.
 
 Usage: bl-tint2-session [OPTION(S)]...[FILES]
 
 Optional arguments:
+
     --help | -h
         show this message
     <SESSIONFILE>
@@ -56,9 +121,10 @@ To start the default tint2 session at login,
 add the following line to autostart:
 
     bl-tint2-session
-'
+')"
 
 # look for a help option somewhere
+
 for i in "$@"
 do
     case "$i" in
@@ -71,6 +137,7 @@ done
 
 # Kill only with exact match, and only if process belongs to executor.
 # Usage: safeKill <processname>
+
 function safeKill(){
     pkill -x -u "$USER" "$1"
 }
@@ -84,7 +151,8 @@ findArgs(){
             exit 0
             ;;
         -*)
-            echo "$0: ${1}: no such option"$'\n' >&2
+            printf "\n$(gettext "%s: %s: no such option")\n" "$0" "${1}" >&2
+
             echo -e "$USAGE"
             exit 1
             ;;
@@ -105,7 +173,9 @@ fullPath(){
             path="$HOME/$path"
         fi
     fi
-    [[ -r $path ]] || { echo "$0: WARNING: cannot read $path" >&2 ; return 1;}
+
+    [[ -r $path ]] || { printf "\n$(gettext "%s: WARNING: cannot read %s")\n" "$0" "$path" >&2 ; return 1;}
+
     printf '%s' "$path"
 }
 
@@ -126,11 +196,15 @@ loadSession(){
         done < "$sessfile"
         set +m
         (( tints > 0 )) || {
-            echo "$0: ERROR: session file $sessfile did not launch any tint2s." >&2
+
+            printf "$(gettext "%s: ERROR: session file %s did not launch any tint2s.")" "$0" "$sessfile" >&2
+
             exit 1
         }
     else
-        echo "$0: ERROR: session file $sessfile is empty or does not exist." >&2
+
+        printf "$(gettext "%s: ERROR: session file %s is empty or does not exist.")" "$0" "$sessfile" >&2
+
         exit 1
     fi
 }
@@ -138,11 +212,17 @@ loadSession(){
 ########################################################################
 
 if [[ ! -f $SESSIONFILE ]] || ! grep -q '[^[:space:]]' "$SESSIONFILE"; then
-    echo "$0: There is no non-empty default session file: ${SESSIONFILE}, generating now..." >&2
+
+    printf "$(gettext "%s: There is no non-empty default session file: %s, generating now...")" "$0" "${SESSIONFILE}" >&2
+
     if [[ -f $DEFAULTTINT2 ]]; then
+
         echo "${DEFAULTTINT2#"$HOME"/}" > "$SESSIONFILE"
+
     else
-        echo "$0: ERROR: unable to generate default session file." >&2
+
+        printf "$(gettext "%s: ERROR: unable to generate default session file.")" "$0" >&2
+
         exit 1
     fi
 fi
@@ -152,3 +232,4 @@ if (( $# == 0 )); then
 else
     findArgs "$@"
 fi
+
